variables:
  IMAGE_NAME: deekode/survey-app
  IMAGE_TAG: version-1.0

stages:
  - run
  - build

run_tests:
  stage: test
  script:
    - bash ./survey.sh -y

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

